/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(miniFR3.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b06df3de011ff1c28665d4a2eaa2ef05)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/FR3/miniFR3.h>
// pydoc.h is automatically generated in the build directory
#include <miniFR3_pydoc.h>

void bind_miniFR3(py::module& m)
{

    using miniFR3    = gr::FR3::miniFR3;


    py::class_<miniFR3, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<miniFR3>>(m, "miniFR3", D(miniFR3))

        .def(py::init(&miniFR3::make),
           D(miniFR3,make)
        )
        



        ;




}








