/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-FR3
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FR3_API_H
#define INCLUDED_FR3_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_FR3_EXPORTS
#define FR3_API __GR_ATTR_EXPORT
#else
#define FR3_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FR3_API_H */
